updated workflow

diff --git a/.github/workflows/cicd-workflow.yaml b/.github/workflows/cicd-workflow.yaml
--- a/.github/workflows/cicd-workflow.yaml
+++ b/.github/workflows/cicd-workflow.yaml
@@ -87,14 +87,17 @@ jobs:
           for service in ./services/*/ ; do
             alb_name=$(basename "$service")-ALB
             alb_dns=$(aws elbv2 describe-load-balancers --names $alb_name --query "LoadBalancers[0].DNSName" --output text)
+            if [ -z "$alb_dns" ]; then
+              echo "ALB DNS not found for $service_name"
+              exit 1
+            fi
             echo "ALB DNS: $alb_dns"
-            echo "::set-output name=alb_dns::$alb_dns"
-            diagrid appid update $service \
-            --app-endpoint "http://$alb_dns" \
-            --api-key ${{ secrets.DIAGRID_API_KEY }} \
-            --project ${{ secrets.DIAGRID_PROJECT }}
+            # Update Diagrid App ID with the ALB DNS and other required parameters
+            diagrid appid update $service_name \
+              --app-endpoint "http://$alb_dns" \
+              --api-key "${{ secrets.DIAGRID_API_KEY }}" \
+              --project "${{ secrets.DIAGRID_PROJECT_NAME }}"
           
-           
           done
 
           
